default: &default
  apple_podcasts: "https://podcasts.apple.com/cn/podcast/teahour/id1486623337"
  overcast: "https://overcast.fm/itunes1486623337/teahour"
  castro: "https://castro.fm/podcast/ba84cbad-e6bd-41ee-a961-8f70ac073248"
  pocket_casts: "https://pca.st/0nyfihxq"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default 