default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

staging:
  adapter: sidekiq
  redis:
    url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/2") %>
    password: <%= ENV.fetch("REDIS_PASSWORD", "") %>
    ssl: <%= ENV.fetch("REDIS_SSL", "false") == "true" %>
    namespace: casmitter_staging_queue
  concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
  queues:
    - [default, 1]
    - [mailers, 2]
    - [active_storage, 3]
    - [high, 4]
    - [low, 5]
  <<: *default

production:
  <<: *default
